services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    command: /bin/bash -c "npm run migrate:run && node ./dist/index.js"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:15.1
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - db-store:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db-store:
